https://docs.python.org/3/library/stdtypes.html#sequence-types-list-tuple-range

A __sequence__ is an ordered collection of items.

The word __ordered__ here is important.

If a sequence wasn't ordered, you couldn't refer to individual items by their index position.

___

string _ an ordered sequence of characters

___

In Python, anything that you can iterate over is an iterable.<br>That means that if you can use it in a for loop, then it's iterable.

All sequence types can be iterated over.

BUT Not all iterables are sequences.<br>
For example, you can use a dictionary in a __for__ loop, but it's not a sequence.

___

### Lists

https://docs.python.org/3/library/stdtypes.html#typesseq-list

There's one big difference between strings and lists: __strings are immutable__, which means they can't be changed. __Lists__, on the other hand, __are mutable__.

The following __immutable types__ are built into Python: 
- int, 
- float, 
- bool (True or False): a subclass of int, 
- string,
- tuple, 
- frozenset 
- bytes. 

### Immutable Objects

The ID for an object may be different each time you run the program, but while your program is running, the object will have the same id.

If python has to destroy the object and re-create it, then it's ID will also change. So that gives us a good way to tell if an object is changed, or if python has to create a new object.

In [6]:
a = 5
b = 5
print(id(a))
print(id(b))

140709031027232
140709031027232


In [7]:
result = True
another_result = result
print(id(result))
print(id(another_result))

140709030504784
140709030504784


Both variables have the same ID. They're both bound to the same value - True - so that makes sense that it should have the same ID. __Remember that we're printing the ID of True (of the value, not the variable name) here__. The variables - result and another_result - are just names that we've bound to that value. Alright, so if bool values could be changed, then changing the values should mean that the ID doesn't change.

In [8]:
result = False
print(id(result))

140709030504816


We've got a different ID for a result. Because bools are immutable, we weren't able to change the value of True. What Python's done instead, is rebound result to a new value - False.

In [13]:
result = 'Correct'
another_result = result
print(id(result))
print(id(another_result))

# let's attempt to mutate result
result += 'ish'
print(id(result))

1720050216304
1720050216304
1720050866288


The id of result has changed, but another_result still has the same id that it had to start with.

In [16]:
print(another_result) # because they have different ids with result
print(id(another_result))

Correct
1720050216304


___

### Mutable Objects

Python has the following __mutable objects__ built in:

- list
- dict
- set
- bytearray

So we can change the value of mutable objects, without the object being destroyed and re-created.

In [1]:
shoppingList = ['milk', 
               'pasta',
               'eggs',
               'spam', 
               'bread', 
               'rice']

another_list = shoppingList
print(id(shoppingList))
print(id(another_list))
print()

shoppingList += ['cookies']
print(shoppingList)
print(id(shoppingList))
print()

print(another_list)
print(id(another_list))

2296114118408
2296114118408

['milk', 'pasta', 'eggs', 'spam', 'bread', 'rice', 'cookies']
2296114118408

['milk', 'pasta', 'eggs', 'spam', 'bread', 'rice', 'cookies']
2296114118408


In [77]:
a = b = [1, 2, 3]
b[0] = 5 
print(b)
print(a)

[5, 2, 3]
[5, 2, 3]


__Strings are immutable__. When we tried to change a string, Python created a new object - a new string - and re-attached the name to it. You can't change the value of an immutable object.

__Lists are mutable__ - they can be changed. When we appended a new item in this code, Python was able to change the contents of the list, without creating a new one.

___

### len(), min(), max() functions

In [3]:
even = [2, 4, 6, 8]
odd = [1, 3, 5, 7, 9]

print(min(even))
print(max(even))

2
8


__len__ returns __the number of items in the sequence__. For a string, that would be the number of characters in the string. For a list though, it's the number of items.

In [4]:
print(len(even), len(odd))

4 5


____

### count() method

Let's see how many times the letter s appears in Mississippi.

In [5]:
print('Mississippi'.count('s'))
print('Mississippi'.count('m'))
print('Mississippi'.count('iss'))

4
0
2


In [6]:
print(even.count(3))
print(even.count(2))

0
1


___

### Operations on Mutable Sequences

### append method()

append is a method that can only be used with a mutable sequence type - such as a list - to add new values 

___

_A method is the same as a function, except that it's bound to an object. That means we need an object, in order to call the method._

___

We've used a few functions above: min and max, and the len function.

_When you call a function, you just type its name, and provide any arguments in parentheses._

___

_When we call a method, we tell it which object it's called on. In other words, which object it should be using when it performs its function._

The syntax of a method is simple. You start with the object you're using, then a dot, then the name of the method. If the method needs arguments, you put them in parentheses after the method name.

___

In [32]:
print(even)

[2, 4, 6, 8]


In [33]:
even.append(10)
print(even)

[2, 4, 6, 8, 10]


___

#### Appending to a List

In [35]:
current_choice = '-'
computer_parts = []

while current_choice != '0':
    if current_choice in '12345':
        print('adding {}'.format(current_choice))
        
        if current_choice == '1':
            computer_parts.append('computer')
        elif current_choice == '2':
            computer_parts.append('monitor')
        elif current_choice == '3':
            computer_parts.append('keyboard')
        elif current_choice == '4':
            computer_parts.append('mouse')
        elif current_choice == '5':
            computer_parts.append('mouse mat')
    else:
        print('Please add options from the list below:')
        print('1: computer')
        print('2: monitor')
        print('3: keyboard')
        print('4: mouse')
        print('5: mouse mat')
        print('0: to finish')
        
    current_choice = input()
    
print(computer_parts)

Please add options from the list below:
1: computer
2: monitor
3: keyboard
4: mouse
5: mouse mat
0: to finish
1
adding 1
4
adding 4
0
['computer', 'mouse']


### index method()

In [38]:
# Partially Efficient code

availableParts = ['computer',
                  'monitor',
                  'keyboard',
                  'mouse',
                  'mouse mat', 
                  'hdmi cable'
                 ]

current_choice = '-'
computer_parts = []

while current_choice != '0':
    if current_choice in '123456':
        print('adding {}'.format(current_choice))
        
        if current_choice == '1':
            computer_parts.append('computer')
        elif current_choice == '2':
            computer_parts.append('monitor')
        elif current_choice == '3':
            computer_parts.append('keyboard')
        elif current_choice == '4':
            computer_parts.append('mouse')
        elif current_choice == '5':
            computer_parts.append('mouse mat')
        elif current_choice == '6':
            computer_parts.append('hdmi cable')
    else:
        print('Please add options from the list below:')
        for part in availableParts:
            print('{0}: {1}'.format(availableParts.index(part) + 1, part))
        print('0: to finish')
        
    current_choice = input()
    
print(computer_parts)

Please add options from the list below:
1: computer
2: monitor
3: keyboard
4: mouse
5: mouse mat
6: hdmi cable
0: to finish
1
adding 1
2
adding 2
0
['computer', 'monitor']


 What we've done above isn't very efficient, and that's because Python has to look up each item in the list, in order to get its index position.

### The enumerate Function

_enumerate returns each item with its index position._

If there are hundreds or thousands of items, finding the index positions will take a while.

In [41]:
availableParts = ['computer',
                  'monitor',
                  'keyboard',
                  'mouse',
                  'mouse mat', 
                  'hdmi cable'
                 ]

current_choice = '-'
computer_parts = []

while current_choice != '0':
    if current_choice in '123456':
        print('adding {}'.format(current_choice))
        
        if current_choice == '1':
            computer_parts.append('computer')
        elif current_choice == '2':
            computer_parts.append('monitor')
        elif current_choice == '3':
            computer_parts.append('keyboard')
        elif current_choice == '4':
            computer_parts.append('mouse')
        elif current_choice == '5':
            computer_parts.append('mouse mat')
        elif current_choice == '6':
            computer_parts.append('hdmi cable')
    else:
        print('Please add options from the list below:')
        for number, part in enumerate(availableParts):
            print('{0}: {1}'.format(number + 1, part))
        print('0: to finish')
        
    current_choice = input()
    
print(computer_parts)

Please add options from the list below:
1: computer
2: monitor
3: keyboard
4: mouse
5: mouse mat
6: hdmi cable
0: to finish
1
adding 1
6
adding 6
7
Please add options from the list below:
1: computer
2: monitor
3: keyboard
4: mouse
5: mouse mat
6: hdmi cable
0: to finish
0
['computer', 'hdmi cable']


In [48]:
availableParts = ['computer',
                  'monitor',
                  'keyboard',
                  'mouse',
                  'mouse mat', 
                  'hdmi cable'
                 ]

for index, value in enumerate(availableParts):
    print(index, value)

0 computer
1 monitor
2 keyboard
3 mouse
4 mouse mat
5 hdmi cable


So for loop starts with the word for, and then the names of one or more variables.

enumerate returns pairs of values - we get the index position and the item, as a pair of values. The first value is the index position and the second value is the item.

___

Good news is, __we can use enumerate with any iterable type. All sequences are iterable__, so let's see another example here.

In [49]:
word = 'testing'
for index, value in enumerate(word):
    print(index, value)

0 t
1 e
2 s
3 t
4 i
5 n
6 g


___

In [52]:
availableParts = ['computer',
                  'monitor',
                  'keyboard',
                  'mouse',
                  'mouse mat', 
                  'hdmi cable',
                  'dvd drive'
                 ]

valid_choices = [str(i) for i in range(1, len(availableParts) + 1)]
print(valid_choices)
current_choice = '-'
computer_parts = []

while current_choice != '0':
    if current_choice in valid_choices:
        print('adding {}'.format(current_choice))
        index = int(current_choice) - 1
        chosen_part = availableParts[index]
        computer_parts.append(chosen_part)
    else:
        print('Please add options from the list below:')
        for number, part in enumerate(availableParts):
            print('{0}: {1}'.format(number + 1, part))
        print('0: to finish')
        
    current_choice = input()
    
print(computer_parts)

['1', '2', '3', '4', '5', '6', '7']
Please add options from the list below:
1: computer
2: monitor
3: keyboard
4: mouse
5: mouse mat
6: hdmi cable
7: dvd drive
0: to finish
1
adding 1
8\
Please add options from the list below:
1: computer
2: monitor
3: keyboard
4: mouse
5: mouse mat
6: hdmi cable
7: dvd drive
0: to finish
7
adding 7
0
['computer', 'dvd drive']


___

### remove() method

__Removing Items from a List__

_list.remove(x)_

Remove the first item from the list whose value is equal to x. It raises a ValueError if there is no such item.

In [55]:
availableParts = ['computer',
                  'monitor',
                  'keyboard',
                  'mouse',
                  'mouse mat', 
                  'hdmi cable',
                  'dvd drive'
                 ]

valid_choices = [str(i) for i in range(1, len(availableParts) + 1)]
current_choice = '-'
computer_parts = []

while current_choice != '0':
    if current_choice in valid_choices:
        index = int(current_choice) - 1
        chosen_part = availableParts[index]
        if chosen_part in computer_parts:
            print('removing {}'.format(current_choice))
            computer_parts.remove(chosen_part)
        else:
            print('adding {}'.format(current_choice))
            computer_parts.append(chosen_part)
        print("Your list now contains: {}".format(computer_parts))
    else:
        print('Please add options from the list below:')
        for number, part in enumerate(availableParts):
            print('{0}: {1}'.format(number + 1, part))
        print('0: to finish')
        
    current_choice = input()
    
print(computer_parts)

Please add options from the list below:
1: computer
2: monitor
3: keyboard
4: mouse
5: mouse mat
6: hdmi cable
7: dvd drive
0: to finish
1
adding 1
Your list now contains: ['computer']
8
Please add options from the list below:
1: computer
2: monitor
3: keyboard
4: mouse
5: mouse mat
6: hdmi cable
7: dvd drive
0: to finish
5
adding 5
Your list now contains: ['computer', 'mouse mat']
5
removing 5
Your list now contains: ['computer']
0
['computer']


In [57]:
news = ['bbc', 'cnn', 'media', 'bbc']
news.remove('bbc')
print(news)

['cnn', 'media', 'bbc']


___

In [9]:
even = [2, 4, 6, 8]
odd = [1, 3, 5, 7, 9]

In [10]:
even.append(odd)
print(even)

[2, 4, 6, 8, [1, 3, 5, 7, 9]]


### extend() method

In [14]:
even = [2, 4, 6, 8]
odd = [1, 3, 5, 7, 9]

In [15]:
# combining them by using the extend method

even.extend(odd)
print(even)

[2, 4, 6, 8, 1, 3, 5, 7, 9]


### sort() method

__Sorting lists__

In [16]:
even.sort()
print(even)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [17]:
even.sort(reverse=True)
print(even)

[9, 8, 7, 6, 5, 4, 3, 2, 1]


__The sort method doesn't create a copy of the list - it rearranges the items in the list.__

In [68]:
even = [2, 4, 6, 8]
odd = [1, 3, 5, 7, 9]

even.extend(odd)
print(even)
another_even = even
print(another_even)

print()

even.sort(reverse=True)
print(even)
print(another_even)

# That's because there's only one list and we mutated the list by sorting it.

[2, 4, 6, 8, 1, 3, 5, 7, 9]
[2, 4, 6, 8, 1, 3, 5, 7, 9]

[9, 8, 7, 6, 5, 4, 3, 2, 1]
[9, 8, 7, 6, 5, 4, 3, 2, 1]


___

https://docs.python.org/3/library/functions.html

___

### sorted() function

#### Sorting things

So we've seen that lists have their own sort method which sorts the list in place, but you may want to sort other things besides lists. _To do that, you can use the sorted function._

__So the sorted function can be used to sort any iterable object.__

In [69]:
pangram = 'The quick brown fox jumps over the lazy dog'

#  A pangram is a phrase that contains all the letters of an alphabet, at least once. 

In [70]:
letters = sorted(pangram)
print(letters)

[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'T', 'a', 'b', 'c', 'd', 'e', 'e', 'e', 'f', 'g', 'h', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'o', 'o', 'o', 'p', 'q', 'r', 'r', 's', 't', 'u', 'u', 'v', 'w', 'x', 'y', 'z']


Python sorted function will take any iterable but will always return a list, and the list is in alphabetical order.
<br>
Uppercase letters sort before lowercase.

In [72]:
numbers = [2.3, 4.5, 8.7, 3.1, 9.2, 1.6 ]
sorted_numbers = sorted(numbers)
print(sorted_numbers)
print(numbers)

[1.6, 2.3, 3.1, 4.5, 8.7, 9.2]
[2.3, 4.5, 8.7, 3.1, 9.2, 1.6]


Notice that we get a list returned here, and the difference here was this time we passed a list to the sorted function, but got a different list back.

Sorted function created a new list and left the original one unchanged. Because sorted returns a new list, we assigned its return value to another variable: sorted_numbers.

On the other hand, the sort method sorts the list in place. That means we don't assign the return value to another variable. Assigning it to a variable doesn't give it the result you might expect. So let's do that to see. 

In [75]:
numbers.sort()
print(numbers)

[1.6, 2.3, 3.1, 4.5, 8.7, 9.2]


In [76]:
numbers = [2.3, 4.5, 8.7, 3.1, 9.2, 1.6 ]

another_sorted_numbers = numbers.sort()

print(numbers)
print(another_sorted_numbers)

[1.6, 2.3, 3.1, 4.5, 8.7, 9.2]
None


You'll find that most of the methods that modify an object in place, like sort does, return None. So there's very rarely, if ever, a need to assign the result of a sort method to a variable.

___

### Case-Insensitive Sorting

Whenever you want to perform a case insensitive sort, just add __key=str.casefold without parentheses__ as an argument to sort method or sorted function.

Use the casefold method of the string class.

Use it if you need to sort some text, without worrying about capitalisation.

In [20]:
print(sorted('The quick brown fox jumps over the lazy dog'))

[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'T', 'a', 'b', 'c', 'd', 'e', 'e', 'e', 'f', 'g', 'h', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'o', 'o', 'o', 'p', 'q', 'r', 'r', 's', 't', 'u', 'u', 'v', 'w', 'x', 'y', 'z']


In [21]:
print(sorted('The quick brown fox jumps over the lazy dog', 
             key = str.casefold))

[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'a', 'b', 'c', 'd', 'e', 'e', 'e', 'f', 'g', 'h', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'o', 'o', 'o', 'p', 'q', 'r', 'r', 's', 'T', 't', 'u', 'u', 'v', 'w', 'x', 'y', 'z']


It's very important that we don't include those parentheses after the function name. That would call the function, which isn't what we want here. What we're doing is telling the sorted function the name of another function it should use, when comparing the values.

In [24]:
names = ['Graham',
        'John',
        'terry',
        'eric',
        'Terry',
        'michael'
        ]

print(names.sort())

# !!!! here we got an error, because you should first sort the list and then only print the list name.

None


In [27]:
names = ['Graham',
        'John',
        'terry',
        'eric',
        'Terry',
        'michael'
        ]

names.sort()
print(names)

print()

names.sort(key = str.casefold)
print(names)

['Graham', 'John', 'Terry', 'eric', 'michael', 'terry']

['eric', 'Graham', 'John', 'michael', 'Terry', 'terry']


___

### Creating Lists

In [30]:
empty_list = []

even = [2, 4, 6, 8]
odd = [1, 3, 5, 7, 9]

# You can also create a list by concatenating existing lists.
numbers = even + odd
print(numbers)

print()

sorted_numbers = sorted(numbers)
print(sorted_numbers)

[2, 4, 6, 8, 1, 3, 5, 7, 9]

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [31]:
digits = sorted("432985617")
print(digits)

['1', '2', '3', '4', '5', '6', '7', '8', '9']


In [33]:
list("432985617")

['4', '3', '2', '9', '8', '5', '6', '1', '7']

____

In [35]:
print(numbers)

more_numbers = list(numbers)
print(more_numbers)

[2, 4, 6, 8, 1, 3, 5, 7, 9]
[2, 4, 6, 8, 1, 3, 5, 7, 9]


It's one way to copy a list. We've now got two lists with the same items; numbers and more_numbers. They're not the same list, though.

In [36]:
# First way 

print(id(numbers))
print(id(more_numbers))

2296131859272
2296132335368


In [37]:
# Second way - We can also use is to see if they're the same

print(numbers is more_numbers)

False


In [38]:
# they're not the same list. They are equal though, because they contain the same items in the same order.

print(numbers == more_numbers)

True


In [45]:
# Third way - There's another way to copy lists and that's to use a slice

print(numbers)

more_numbers = numbers[:]
print(more_numbers)

print()

print(id(numbers))
print(id(more_numbers))

[2, 4, 6, 8, 1, 3, 5, 7, 9]
[2, 4, 6, 8, 1, 3, 5, 7, 9]

2296131859272
2296131656712


The most readable way is to use the **copy method**.

In [46]:
more_numbers = numbers.copy()
print(more_numbers)

print()

print(id(numbers))
print(id(more_numbers))

[2, 4, 6, 8, 1, 3, 5, 7, 9]

2296131859272
2296131657288


https://stackoverflow.com/questions/2612802/list-changes-unexpectedly-after-assignment-why-is-this-and-how-can-i-prevent-it/43220129#43220129

___

== will return True if the lists contain the same items, in the same order. 

The is operator will return True if two variables are referring to the same list.

____

### Replacing a slice
**Mutable Sequence Operations**

https://docs.python.org/3/library/stdtypes.html#mutable-sequence-types

In [54]:
computer_parts = ['computer',
                  'monitor',
                  'keyboard',
                  'mouse',
                  'mouse mat'
                 ]

# Let's now replace the mouse in our list with a trackball.

computer_parts[3] = 'trackball'
print(computer_parts)

# s[i] = x        item i of s is replaced by x

['computer', 'monitor', 'keyboard', 'trackball', 'mouse mat']


**!!! Strings are immutable, so we can't replace one character with another.**

In [55]:
computer_parts = ['computer',
                  'monitor',
                  'keyboard',
                  'mouse',
                  'mouse mat'
                 ]

computer_parts[3:] = 'trackball'
print(computer_parts)

# s[i:j] = t      slice of s from i to j is replaced by the contents of the iterable t

['computer', 'monitor', 'keyboard', 't', 'r', 'a', 'c', 'k', 'b', 'a', 'l', 'l']


In [56]:
computer_parts = ['computer',
                  'monitor',
                  'keyboard',
                  'mouse',
                  'mouse mat'
                 ]

computer_parts[3:] = ['trackball']
print(computer_parts)

['computer', 'monitor', 'keyboard', 'trackball']


___

### Deleting Items from a List

In [63]:
data = [4, 5, 104, 105, 110, 120, 130, 130, 150,
       160, 170, 183, 185, 187, 188, 191, 350, 360]

the first two values are much lower than the others, and we can remove them from the list

In [64]:
del data[:2]
print(data)

[104, 105, 110, 120, 130, 130, 150, 160, 170, 183, 185, 187, 188, 191, 350, 360]


In [65]:
del data[14:]
print(data)

[104, 105, 110, 120, 130, 130, 150, 160, 170, 183, 185, 187, 188, 191]


____

In [66]:
data = [4, 5, 104, 105, 110, 120, 130, 130, 150,
       160, 170, 183, 185, 187, 188, 191, 350, 360]

min_valid = 100
max_valid = 200

for index, value in enumerate(data):
    if value < min_valid or value > max_valid:
        del data[index]

print(data)        

[5, 104, 105, 110, 120, 130, 130, 150, 160, 170, 183, 185, 187, 188, 191, 360]


**!!! But it's not going to work.**

You can see the first value is 5, which should have been removed. At the end of the list we've still got 360, as well. Now the debugger will help to understand what's going on here.

Alright so index is currently zero and value is 4. That'll pass the condition, so del data[0] will be executed.
<br>The list now starts with the value 5. You can see that 4 has been removed.

Step over once more. Now check the values of index and value.
<br>Index is 1 and the value's 104. 5 has been skipped because it's now at position zero.

**The message to take away from this** is to be very careful when changing the size of an object, that you're iterating over. If you want to replace items with different ones, that's normally fine, but deleting items from a list, or any other mutable sequence type, while iterating forwards over it will cause problems, as we've seen here.

___

### Safely removing values from a list (from an *ordered* set of data)

In [67]:
data = [4, 5, 104, 105, 110, 120, 130, 130, 150,
       160, 170, 183, 185, 187, 188, 191, 350, 360]

min_valid = 100
max_valid = 200

# So I'm going to assume that we don't have enough memory to copy the list. 
# You may not have enough RAM for copying the entire list.

stop = 0
for index, value in enumerate(data):
    if value >= min_valid:
        stop = index
        break
        
print(stop) # for debugging
del data[:stop] # Remember that a slice extends up to, but not including, the stop value.
print(data)

2
[104, 105, 110, 120, 130, 130, 150, 160, 170, 183, 185, 187, 188, 191, 350, 360]


___

Deleting the items from the end of the list needs a bit more thought.
<br>If there are billions of items, we don't want to work through the entire list to find the first value to be deleted.
<br>Instead, we can process the list from the end.

In [70]:
# We want to work backwards, which means that we'll start at the index position 1 less than the length of the list.
# We can't use 0 as the stop value. Remember that the last value in a range or slice isn't included.
# If we use 0, the first item in the list won't be included.
# And that's why we're using -1 as the stop value.

start = 0
for index in range(len(data) - 1, -1, -1): 
    print(index)

15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0


If we find a value that's within the valid range - so a value that's less than or equal to 200 - we can break out of the loop.

In [71]:
start = 0
for index in range(len(data) - 1, -1, -1):
    if data[index] <= max_valid:
        start = index
        break

del data[start + 1 :]
print(data)

[104, 105, 110, 120, 130, 130, 150, 160, 170, 183, 185, 187, 188, 191]


or

In [ ]:
start = 0
for index in range(len(data) - 1, -1, -1):
    if data[index] <= max_valid:
        start = index + 1
        break

del data[start :]
print(data)

___

### Edge case, Corner case

https://en.wikipedia.org/wiki/Edge_case#:~:text=An%20edge%20case%20is%20a,can%20be%20expected%20or%20unexpected.<br>
https://en.wikipedia.org/wiki/Corner_case

You need to test for all the scenarios in your code, to make sure there are no bugs.
<br> Make sure you test edge cases and corner cases: An **edge case** is "a problem or situation that occurs at an extreme operation parameter", and a **corner case** is similar, but when there's more than one parameter involved.

___

### Removing Items from a List Backwards

You should be careful, when changing a list that you're iterating over. One way to be careful, is to iterate backwards.
<br> If we remove an item at index 10, all the items above that would shuffle down. But the indexes from 9 to 0 wouldn't be affected.

Iterating backwards is a valuable technique, and allows the size of your sequence to be changed without causing a problem. 

In [8]:
# The values to remove appear randomly in the list.

data = [104, 101, 4, 105, 308, 103, 5,
       107, 100, 306, 106, 102, 108]

min_valid = 100
max_valid = 200

# it's not sorted

for index in range(len(data)-1, -1, -1):
    if data[index] < min_valid or data[index] > max_valid:
        print(index, data)
        del data[index]
        
print()

print(data) # The four rogue values have gone from the list.

9 [104, 101, 4, 105, 308, 103, 5, 107, 100, 306, 106, 102, 108]
6 [104, 101, 4, 105, 308, 103, 5, 107, 100, 106, 102, 108]
4 [104, 101, 4, 105, 308, 103, 107, 100, 106, 102, 108]
2 [104, 101, 4, 105, 103, 107, 100, 106, 102, 108]

[104, 101, 105, 103, 107, 100, 106, 102, 108]


### The Reversed() Function

this function gives us a way to iterate over a sequence in reverse

In [14]:
data = [104, 101, 4, 105, 308, 103, 5,
       107, 100, 306, 106, 102, 108]

for index, value in enumerate(reversed(data)):
    print(index, value)

0 108
1 102
2 106
3 306
4 100
5 107
6 5
7 103
8 308
9 105
10 4
11 101
12 104


**!!!  When you use a reversed iterator, the index positions relate to the data in reverse order.**

It's easy to get the correct index positions. All we need to do is just subtract index from 12.

In [15]:
data

[104, 101, 4, 105, 308, 103, 5, 107, 100, 306, 106, 102, 108]

In [16]:
reversed(data)

In [18]:
data = [104, 101, 4, 105, 308, 103, 5,
       107, 100, 306, 106, 102, 108]

# len(data) is 13

min_valid = 100
max_valid = 200

top_index = len(data) - 1  
for index, value in enumerate(reversed(data)):
    if value < min_valid or value > max_valid:
        del data[top_index - index]
        
print(data)

# if not reversed - 108 is at index 12
# if reversed - at index 0

[104, 101, 105, 103, 107, 100, 106, 102, 108]


___

# 110. Algorithm Performance ---- (to be looked through, DON'T FORGET)

___

### Nested Lists & Code Style

In [19]:
even = [2, 4, 6, 8]
odd = [1, 3, 5, 7, 9]

numbers = even + odd

print(numbers)

[2, 4, 6, 8, 1, 3, 5, 7, 9]


In [20]:
even = [2, 4, 6, 8]
odd = [1, 3, 5, 7, 9]

numbers = [even, odd]

print(numbers)

[[2, 4, 6, 8], [1, 3, 5, 7, 9]]


In [22]:
for i in numbers:
    print(i)
    
    for value in i:
        print(value)

[2, 4, 6, 8]
2
4
6
8
[1, 3, 5, 7, 9]
1
3
5
7
9


https://www.python.org/dev/peps/pep-0008/

https://google.github.io/styleguide/pyguide.html  **Read this!!!**

___

In [23]:
menu = [
        ["egg", "bacon"],
        ["egg", "sausage", "bacon"],
        ["egg", "spam"],
        ["egg", "bacon", "spam"],
        ["egg", "bacon", "sausage", "spam"],
        ["spam", "bacon", "sausage", "spam"],
        ["spam", "sausage", "spam", "bacon", "spam", "tomato", "spam"],
        ["spam", "egg", "spam", "spam", "bacon", "spam"],
]

In [24]:
for meal in menu:
    if "spam" not in meal:
        print(meal)
        
        for item in meal:
            print(item)
    else:
        print("{0} has a spam score {1}"
             .format(meal, meal.count("spam")))

['egg', 'bacon']
egg
bacon
['egg', 'sausage', 'bacon']
egg
sausage
bacon
['egg', 'spam'] has a spam score 1
['egg', 'bacon', 'spam'] has a spam score 1
['egg', 'bacon', 'sausage', 'spam'] has a spam score 1
['spam', 'bacon', 'sausage', 'spam'] has a spam score 2
['spam', 'sausage', 'spam', 'bacon', 'spam', 'tomato', 'spam'] has a spam score 4
['spam', 'egg', 'spam', 'spam', 'bacon', 'spam'] has a spam score 4


___

#### Challenge

write code to print out all the meals in the menu, but with **spam** removed

In [25]:
menu = [
        ["egg", "bacon"],
        ["egg", "sausage", "bacon"],
        ["egg", "spam"],
        ["egg", "bacon", "spam"],
        ["egg", "bacon", "sausage", "spam"],
        ["spam", "bacon", "sausage", "spam"],
        ["spam", "sausage", "spam", "bacon", "spam", "tomato", "spam"],
        ["spam", "egg", "spam", "spam", "bacon", "spam"],
]

In [26]:
for meal in menu:
    for item in meal:
        if item == 'spam':
            meal.remove('spam')
    print(meal)

['egg', 'bacon']
['egg', 'sausage', 'bacon']
['egg']
['egg', 'bacon']
['egg', 'bacon', 'sausage']
['bacon', 'sausage']
['sausage', 'bacon', 'tomato']
['egg', 'bacon', 'spam']


In [27]:
# Backwards through the list

for meal in menu:
    for index in range(len(meal)-1, -1, -1):
        if meal[index] == 'spam':
            del meal[index]
    print(meal)

['egg', 'bacon']
['egg', 'sausage', 'bacon']
['egg']
['egg', 'bacon']
['egg', 'bacon', 'sausage']
['bacon', 'sausage']
['sausage', 'bacon', 'tomato']
['egg', 'bacon']


In [28]:
for meal in menu:
    for item in meal:
        if item != 'spam':
            print(item)
    print()

egg
bacon

egg
sausage
bacon

egg

egg
bacon

egg
bacon
sausage

bacon
sausage

sausage
bacon
tomato

egg
bacon



The items for each meal are on a separate line here, though, which isn't ideal.
<br> The print function has some extra arguments that we can use.

### print() revisited

In [31]:
name = "Tim"
age = 25

print(name, age, "Python", 2022) # we can provide several values

Tim 25 Python 2022


In [34]:
# sep=' '   The sep parameter is a keyword argument, and its default value is ' '

print(name, age, "Python", 2022, sep=', ')

Tim, 25, Python, 2022


If we want to provide a value for sep, we have to specify its name. Now that's why they're also called named arguments. 

<u>Remember that the separator's only used between the values we print, when we pass more than one value to the print function.

#### <u>It's usual not to put spaces either side of the equal sign, when passing a keyword argument

The other keyword argument that we saw in the documentation, was **end**.

In [51]:
menu = [
        ["egg", "bacon"],
        ["egg", "sausage", "bacon"],
        ["egg", "spam"],
        ["egg", "bacon", "spam"],
        ["egg", "bacon", "sausage", "spam"],
        ["spam", "bacon", "sausage", "spam"],
        ["spam", "sausage", "spam", "bacon", "spam", "tomato", "spam"],
        ["spam", "egg", "spam", "spam", "bacon", "spam"],
]

In [52]:
for meal in menu:
    for item in meal:
        if item != 'spam':
            print(item, end=' ')
    print()
    
# Setting end to a space, tells print to print a space after printing, instead of a newline (default).

egg bacon 
egg sausage bacon 
egg 
egg bacon 
egg bacon sausage 
bacon sausage 
sausage bacon tomato 
egg bacon 


In [53]:
for meal in menu:
    for item in meal:
        if item != 'spam':
            print(item, end=', ')
    print()

egg, bacon, 
egg, sausage, bacon, 
egg, 
egg, bacon, 
egg, bacon, sausage, 
bacon, sausage, 
sausage, bacon, tomato, 
egg, bacon, 


In [54]:
for meal in menu:
    items = ", ".join((item for item in meal if item != 'spam'))
    print(items)

egg, bacon
egg, sausage, bacon
egg
egg, bacon
egg, bacon, sausage
bacon, sausage
sausage, bacon, tomato
egg, bacon


___

### The join method

<u>**The join method actually takes care of iterating. We give it an iterable and it joins all the items in the iterable.**

<u>**It uses the string we call it on as the separator.**

In [59]:
menu = [
        ["egg", "bacon"],
        ["egg", "sausage", "bacon"],
        ["egg", "spam"],
        ["egg", "bacon", "spam"],
        ["egg", "bacon", "sausage", "spam"],
        ["spam", "bacon", "sausage", "spam"],
        ["spam", "sausage", "spam", "bacon", "spam", "tomato", "spam"],
        ["spam", "egg", "spam", "spam", "bacon", "spam"],
]

In [60]:
for meal in menu:
    for index in range(len(meal)-1, -1, -1):
        if meal[index] == 'spam':
            del meal[index]
    
    print(meal)

['egg', 'bacon']
['egg', 'sausage', 'bacon']
['egg']
['egg', 'bacon']
['egg', 'bacon', 'sausage']
['bacon', 'sausage']
['sausage', 'bacon', 'tomato']
['egg', 'bacon']


In [61]:
for meal in menu:
    for index in range(len(meal)-1, -1, -1):
        if meal[index] == 'spam':
            del meal[index]
    
    print(", ".join(meal))

egg, bacon
egg, sausage, bacon
egg
egg, bacon
egg, bacon, sausage
bacon, sausage
sausage, bacon, tomato
egg, bacon


In [62]:
flowers = [
    "Daffodil",
    'Evening Primrose',
    'Hydrangea',
    'Iris',
    'Lavanda', 
    'Sunflower'
]

In [64]:
separator = " | "
output = separator.join(flowers)
print(output)

Daffodil | Evening Primrose | Hydrangea | Iris | Lavanda | Sunflower


**!!! Now note that we haven't had to use a for loop here. Join iterates over the list for us.**

___

#### <u>So the join method creates a string from a list, and separates each item with the string that it's called on.

___

In [65]:
print(','.join(flowers))

Daffodil,Evening Primrose,Hydrangea,Iris,Lavanda,Sunflower


**!!! there is one thing to be aware of - all the items in the iterable must be strings, if you want to join the items**

___

### The split method

In [80]:
panagram = 'The quick brown fox jumps over the lazy dog.'

words = panagram.split(' ')
print(words)

# we get a list containing all the words in the string

['The', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog.']


In [81]:
panagram = """The quick brown
fox jumps\t over
the lazy dog.
"""
print(panagram)

print()

print(panagram.split(' '))

The quick brown
fox jumps	 over
the lazy dog.


['The', 'quick', 'brown\nfox', 'jumps\t', 'over\nthe', 'lazy', 'dog.\n']


In [82]:
panagram = """The quick brown
fox jumps\t over
the lazy dog.
"""
print(panagram)

print()

print(panagram.split('\t'))

The quick brown
fox jumps	 over
the lazy dog.


['The quick brown\nfox jumps', ' over\nthe lazy dog.\n']


In [84]:
numbers = '9, 345, 78, 098, 56, 234, 11'
print(numbers.split(', '))

['9', '345', '78', '098', '56', '234', '11']


**<u>when you split a string, you get a list of strings**

In [96]:
generated_list =['9', ' ',
                '2', '3', '3', ' ', 
                '3', '4', '7', ' ', 
                '1', '5'
                ]

values = ''.join(generated_list)
print(values, type(values))

print()

values_list = values.split(' ')
print(values_list)

9 233 347 15 <class 'str'>

['9', '233', '347', '15']


In [97]:
values_list_int = [int(i) for i in values_list]
print(values_list_int)

[9, 233, 347, 15]


In [98]:
# replace each value, in turn, with its integer equivalent

print(values_list)
for index in range(len(values_list)):
    values_list[index] = int(values_list[index])
print(values_list)

['9', '233', '347', '15']
[9, 233, 347, 15]


In [101]:
# create a new list

values_list = ['9', '233', '347', '15']
integer_values = []
for value in values_list:
    integer_values.append(int(value))
print(integer_values)

[9, 233, 347, 15]


___

### Tuples

**immutable sequence**

**tuples help protect the integrity of your data**

https://docs.python.org/3/library/stdtypes.html#common-sequence-operations

All of the common sequence operations can be performed on tuples.

In [106]:
t = 'a', 'b', 'c'
print(t, type(t))

('a', 'b', 'c') <class 'tuple'>


In [105]:
t = ('a', 'b', 'c')
print(t, type(t))

('a', 'b', 'c') <class 'tuple'>


In [107]:
name = 'Tim'
age = 25
print(name, age, 'Python', 2022)
print((name, age, 'Python', 2022))

Tim 25 Python 2022
('Tim', 25, 'Python', 2022)


In [108]:
welcome = "Welcome to my Nightmare", "Alice Cooper", 1975
bad = "Bad Company", "Bad Company", 1974
budgie = "Nightflight", "Budgie", 1981
imelda = "More Mayhem", "Emilda May", 2011
metallica = "Ride the Lightning", "Metallica", 1984

In [110]:
print(metallica)
print(metallica[0])
print(metallica[1])
print(metallica[2])

('Ride the Lightning', 'Metallica', 1984)
Ride the Lightning
Metallica
1984


___

Unlike a list, a tuple is immutable. If you attempt to change an item in a tuple, you'll get an error.

In [111]:
metallica[0] = 'something else'

TypeError: 'tuple' object does not support item assignment

___

Because tuples don't have the overhead of the methods needed to change them, **tuples use less memory than lists**. That's one reason why you might want to use a tuple. 

https://docs.python.org/3/library/functions.html

Using a tuple, for things that shouldn't change, can help to prevent bugs in your programs.

___

In [1]:
a = b = c = d = e = f = 12
print(c)

12


In [5]:
x, y, z = 1, 2, 25
print(x)
print(y)
print(z)

# those three values on the right hand side, look suspiciously like a tuple.
# That's because they are a tuple.

1
2
25


this is called unpacking a tuple

In [10]:
print('Unpacking a tuple')

data = 1, 2, 76        # data represents a tuple
x, y, z = data         # three separate variables, that each get a value from the data tuple.

print(x)
print(y)
print(z)

# You can't have a tuple on the left of an assignment, because tuples, if you recall, are immutable.

Unpacking a tuple
1
2
76


**<u>you can unpack any sequence type</u>**

In [11]:
print('Unpacking a list')

data_list = [12, 13, 14]
p, q, r = data_list
print(p)
print(q)
print(r)

Unpacking a list
12
13
14


**The second advantage of tuples, is that you can always unpack them successfully.
<br>Because a tuple can't be changed, you always know how many items there are to unpack. **

___

In [12]:
for index, character in enumerate('abcd'):
    print(index, character)

0 a
1 b
2 c
3 d


In [13]:
for t in enumerate('abcd'):
    print(t)

(0, 'a')
(1, 'b')
(2, 'c')
(3, 'd')


In [14]:
index, character = (0, 'a')
print(index)
print(character)

0
a


*So that's what's happening on line one. Each time around the loop, index and character are unpacked from the tuple that enumerate creates.*

In [16]:
for t in enumerate('abcd'):
    index, character = t
    print(index, character)

0 a
1 b
2 c
3 d


___

In [17]:
welcome = "Welcome to my Nightmare", "Alice Cooper", 1975
bad = "Bad Company", "Bad Company", 1974
budgie = "Nightflight", "Budgie", 1981
imelda = "More Mayhem", "Emilda May", 2011
metallica = "Ride the Lightning", "Metallica", 1984

In [18]:
title, artist, year = metallica
print(title)
print(artist)
print(year)

Ride the Lightning
Metallica
1984


___

In [19]:
table = ('Coffee table', 200, 100, 75, 34.50)
print(table[1] * table[2])

name, length, width, height, price = table
print(length * width)

20000
20000


___

### Nested Tuples and Lists

In [20]:
albums = [("Welcome to my Nightmare", "Alice Cooper", 1975),
          ("Bad Company", "Bad Company", 1974),
          ("Nightflight", "Budgie", 1981),
          ("More Mayhem", "Emilda May", 2011),
          ("Ride the Lightning", "Metallica", 1984)
         ]

In [21]:
print(len(albums))

5


In [33]:
for album in albums:
    print("Album: {:23}, Artist: {:13}, Year: {}"
          .format(album[0], album[1], album[2]))

Album: Welcome to my Nightmare, Artist: Alice Cooper , Year: 1975
Album: Bad Company            , Artist: Bad Company  , Year: 1974
Album: Nightflight            , Artist: Budgie       , Year: 1981
Album: More Mayhem            , Artist: Emilda May   , Year: 2011
Album: Ride the Lightning     , Artist: Metallica    , Year: 1984


In [35]:
for album in albums:
    name, artist, year = album
    print(f"Album: {name:23}, Artist: {artist:13}, Year: {year}")

Album: Welcome to my Nightmare, Artist: Alice Cooper , Year: 1975
Album: Bad Company            , Artist: Bad Company  , Year: 1974
Album: Nightflight            , Artist: Budgie       , Year: 1981
Album: More Mayhem            , Artist: Emilda May   , Year: 2011
Album: Ride the Lightning     , Artist: Metallica    , Year: 1984


In [36]:
for name, artist, year in albums:
    print(f"Album: {name:23}, Artist: {artist:13}, Year: {year}")

Album: Welcome to my Nightmare, Artist: Alice Cooper , Year: 1975
Album: Bad Company            , Artist: Bad Company  , Year: 1974
Album: Nightflight            , Artist: Budgie       , Year: 1981
Album: More Mayhem            , Artist: Emilda May   , Year: 2011
Album: Ride the Lightning     , Artist: Metallica    , Year: 1984


___

In [37]:
albums = [
    ("Welcome to my Nightmare", "Alice Cooper", 1975,
     [
         (1, "Welcome to my Nightmare"),
         (2, "Devil's Food"),
         (3, "The Black Widow"),
         (4, "Some Folks"),
         (5, "Only Women Bleed"),
     ]
     ),
    ("Bad Company", "Bad Company", 1974,
     [
         (1, "Can't Get Enough"),
         (2, "Rock Steady"),
         (3, "Ready for Love"),
         (4, "Don't Let Me Down"),
         (5, "Bad Company"),
         (6, "The Way I Choose"),
         (7, "Movin' On"),
         (8, "Seagull"),
     ]
     ),
    ("Nightflight", "Budgie", 1981,
     [
         (1, "I Turned to Stone"),
         (2, "Keeping a Rendezvous"),
         (3, "Reaper of the Glory"),
         (4, "She Used Me Up"),
     ]
     ),
    ("More Mayhem", "Imelda May", 2011,
     [
         (1, "Pulling the Rug"),
         (2, "Psycho"),
         (3, "Mayhem"),
         (4, "Kentish Town Waltz"),
     ]
     ),
]

In [40]:
for name, artist, year, songs in albums:
    print(f"Album: {name}, Artist: {artist}, Year: {year}, Songs: {songs}")
    print()

Album: Welcome to my Nightmare, Artist: Alice Cooper, Year: 1975, Songs: [(1, 'Welcome to my Nightmare'), (2, "Devil's Food"), (3, 'The Black Widow'), (4, 'Some Folks'), (5, 'Only Women Bleed')]

Album: Bad Company, Artist: Bad Company, Year: 1974, Songs: [(1, "Can't Get Enough"), (2, 'Rock Steady'), (3, 'Ready for Love'), (4, "Don't Let Me Down"), (5, 'Bad Company'), (6, 'The Way I Choose'), (7, "Movin' On"), (8, 'Seagull')]

Album: Nightflight, Artist: Budgie, Year: 1981, Songs: [(1, 'I Turned to Stone'), (2, 'Keeping a Rendezvous'), (3, 'Reaper of the Glory'), (4, 'She Used Me Up')]

Album: More Mayhem, Artist: Imelda May, Year: 2011, Songs: [(1, 'Pulling the Rug'), (2, 'Psycho'), (3, 'Mayhem'), (4, 'Kentish Town Waltz')]



___

### Importing data

Python lets us import things from other Python files, which can be a great way to share data between different programs. And it's also a great way to share code between different programs.

In [2]:
from albumsData import albums

In [3]:
print(albums)

[('Welcome to my Nightmare', 'Alice Cooper', 1975, [(1, 'Welcome to my Nightmare'), (2, "Devil's Food"), (3, 'The Black Widow'), (4, 'Some Folks'), (5, 'Only Women Bleed')]), ('Bad Company', 'Bad Company', 1974, [(1, "Can't Get Enough"), (2, 'Rock Steady'), (3, 'Ready for Love'), (4, "Don't Let Me Down"), (5, 'Bad Company'), (6, 'The Way I Choose'), (7, "Movin' On"), (8, 'Seagull')]), ('Nightflight', 'Budgie', 1981, [(1, 'I Turned to Stone'), (2, 'Keeping a Rendezvous'), (3, 'Reaper of the Glory'), (4, 'She Used Me Up')]), ('More Mayhem', 'Imelda May', 2011, [(1, 'Pulling the Rug'), (2, 'Psycho'), (3, 'Mayhem'), (4, 'Kentish Town Waltz')])]


In [14]:
while True:
    print('Please choose your album (invalid choice exists):')
    print('_' * 124)
    print()
    
    for index, (title, artist, year, songs) in enumerate(albums):
        print('{}: {}, {}, {}, {}'
             .format(index + 1, title, artist, year, songs))
        print()
        
    break

Please choose your album (invalid choice exists):
____________________________________________________________________________________________________________________________

1: Welcome to my Nightmare, Alice Cooper, 1975, [(1, 'Welcome to my Nightmare'), (2, "Devil's Food"), (3, 'The Black Widow'), (4, 'Some Folks'), (5, 'Only Women Bleed')]

2: Bad Company, Bad Company, 1974, [(1, "Can't Get Enough"), (2, 'Rock Steady'), (3, 'Ready for Love'), (4, "Don't Let Me Down"), (5, 'Bad Company'), (6, 'The Way I Choose'), (7, "Movin' On"), (8, 'Seagull')]

3: Nightflight, Budgie, 1981, [(1, 'I Turned to Stone'), (2, 'Keeping a Rendezvous'), (3, 'Reaper of the Glory'), (4, 'She Used Me Up')]

4: More Mayhem, Imelda May, 2011, [(1, 'Pulling the Rug'), (2, 'Psycho'), (3, 'Mayhem'), (4, 'Kentish Town Waltz')]



**What happens if I remove those parentheses in for loop?** 

In [15]:
while True:
    print('Please choose your album (invalid choice exists):')
    print('_' * 124)
    print()
    
    for index, title, artist, year, songs in enumerate(albums):
        print('{}: {}, {}, {}, {}'
             .format(index + 1, title, artist, year, songs))
        print()
        
    break

Please choose your album (invalid choice exists):
____________________________________________________________________________________________________________________________



ValueError: not enough values to unpack (expected 5, got 2)

In [17]:
for index, value in enumerate(albums):
    print(index, value)
    
# The first is an int, the index position of each item, 
# but the second item is a tuple, and it actually contains four items; 
# the title, the artist, the year, as well as the list of songs.

0 ('Welcome to my Nightmare', 'Alice Cooper', 1975, [(1, 'Welcome to my Nightmare'), (2, "Devil's Food"), (3, 'The Black Widow'), (4, 'Some Folks'), (5, 'Only Women Bleed')])
1 ('Bad Company', 'Bad Company', 1974, [(1, "Can't Get Enough"), (2, 'Rock Steady'), (3, 'Ready for Love'), (4, "Don't Let Me Down"), (5, 'Bad Company'), (6, 'The Way I Choose'), (7, "Movin' On"), (8, 'Seagull')])
2 ('Nightflight', 'Budgie', 1981, [(1, 'I Turned to Stone'), (2, 'Keeping a Rendezvous'), (3, 'Reaper of the Glory'), (4, 'She Used Me Up')])
3 ('More Mayhem', 'Imelda May', 2011, [(1, 'Pulling the Rug'), (2, 'Psycho'), (3, 'Mayhem'), (4, 'Kentish Town Waltz')])


In [18]:
for index, value in enumerate(albums):
    title, artist, year, songs = value
    print(index, title, artist, year, songs)

0 Welcome to my Nightmare Alice Cooper 1975 [(1, 'Welcome to my Nightmare'), (2, "Devil's Food"), (3, 'The Black Widow'), (4, 'Some Folks'), (5, 'Only Women Bleed')]
1 Bad Company Bad Company 1974 [(1, "Can't Get Enough"), (2, 'Rock Steady'), (3, 'Ready for Love'), (4, "Don't Let Me Down"), (5, 'Bad Company'), (6, 'The Way I Choose'), (7, "Movin' On"), (8, 'Seagull')]
2 Nightflight Budgie 1981 [(1, 'I Turned to Stone'), (2, 'Keeping a Rendezvous'), (3, 'Reaper of the Glory'), (4, 'She Used Me Up')]
3 More Mayhem Imelda May 2011 [(1, 'Pulling the Rug'), (2, 'Psycho'), (3, 'Mayhem'), (4, 'Kentish Town Waltz')]


___